credentials:
  usernames:
    admin:
      email: admin@example.com
      name: 관리자
      password: $2b$12$DMddI.MzK2a4Bag9p2mF/OWm/7IG4hAk1Tah62ksEdxgE9.Bf2UBG # "admin123"
    user:
      email: user@example.com
      name: 일반사용자
      password: $2b$12$h3TgDeqNenYcGiioBPwELOa6zliWlz2ucFBH7lgGxh71lneXf8Fjm  # "user123"

cookie:
  expiry_days: 30
  key: some_signature_key
  name: news_chatbot_cookie

preauthorized:
  emails:
    - newuser@example.com